# Generated by Django 4.2.6 on 2023-11-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("New_Search_Console", "0002_rename_question_keyword_keyword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="keyword",
            field=models.CharField(max_length=200),
        ),
    ]
