# Generated by Django 4.2.6 on 2023-11-01 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("New_Search_Console", "0003_alter_keyword_keyword"),
    ]

    operations = [
        migrations.RenameField(
            model_name="keyword",
            old_name="keyword",
            new_name="keyword_text",
        ),
    ]
